name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Kodu yüklə
        uses: actions/checkout@v3

      - name: Versiya yoxlaması
        run: node -v
